name: CI

on:
  # Runs tests when code is pushed to the main branch
  push: 
    branches:
      - main

  # Allows manual execution from the GitHub Actions UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Node.js and cache dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      # Install dependencies and run tests
      - run: npm ci
      - run: npm test
